"""Gemini sketch-generation prompts."""

# Appended when a previously finished frame of the SAME sequence is supplied. Without
# it every frame is an independent read of the model sheet, so details that the sheet
# shows more than one way (e.g. a hat drawn on the head in one view and on the back in
# another) come out differently from frame to frame.
CONSISTENCY_REF = (
    "\nIMAGE 3 is the ANCHOR: an approved frame from THIS SAME sequence. Use IMAGE 3 "
    "ONLY to keep the character's SCALE and DESIGN identical across the sequence:\n"
    "- SCALE & SIZE: the same character height and on-screen size, and the same size for "
    "the head, hands and every accessory (a hat/cape the EXACT same size as in IMAGE 3). "
    "Do not zoom or rescale between frames.\n"
    "- DESIGN: the same hairstyle, outfit, accessory placement, body proportions, line "
    "weight and drawing style.\n"
    "DO NOT COPY THE ANCHOR'S POSE. This frame's pose comes ENTIRELY from IMAGE 2. These "
    "are CONSECUTIVE animation frames, so the pose is usually only SLIGHTLY different from "
    "the anchor -- and you MUST reproduce those small differences, never flatten them to "
    "match the anchor. Read IMAGE 2 carefully and copy its EXACT pose: the precise angle "
    "of each arm and leg, every hand position, the head tilt and the body lean shown in "
    "THIS rough. If IMAGE 2's arm/hand/head is even a little higher, lower or rotated "
    "versus the anchor, draw it exactly where IMAGE 2 shows it. The character keeps the "
    "anchor's LOOK and SIZE but takes THIS rough's exact pose -- so that when the frames "
    "play back, the motion genuinely moves."
)

# Option B: rough (gesture) + Canny edge map (structure) sent together.
ROUGH_CANNY_REF = (
    "\nOPTION B — TWO POSE GUIDES for this frame:\n"
    "IMAGE 2 is the ROUGH GESTURE SKETCH. Read IMAGE 2 for the EXACT pose nuance: hand "
    "shapes (fist vs open), joint angles, head tilt, body lean, foreshortening, and small "
    "frame-to-frame motion. IGNORE image 2's character identity.\n"
    "IMAGE 3 is the CANNY EDGE MAP of the SAME frame (white background, black silhouette "
    "edges). Use IMAGE 3 for FRAMING ONLY: where the figure sits in the frame, overall "
    "silhouette width/height, and limb placement. Match IMAGE 3's on-screen position and "
    "margins — do NOT re-center, zoom, crop, or rescale relative to IMAGE 3.\n"
    "Combine both: gesture, hands, and depth from IMAGE 2; framing and silhouette from IMAGE 3.\n"
    "CONSTRUCTION MARKS — IMAGE 2 may contain animator construction lines: circles at "
    "joints, axis lines, overlapping corrections, and stray strokes. These are NOT body "
    "parts. Do NOT turn a joint circle or overlapping sketch stroke into an extra arm, "
    "hand, leg or foot.\n"
    "LIMB COUNT — CRITICAL: draw EXACTLY two arms and two legs — no more. Each arm ends "
    "in ONE hand. Before finishing, verify: 2 shoulders, 2 upper arms, 2 forearms, "
    "2 hands, 2 thighs, 2 calves, 2 feet. Never add a phantom limb behind the body.\n"
    "FACE — copy IMAGE 2's facial expression exactly: surprised/shocked (wide eyes, small "
    "open mouth). Do NOT copy expression from IMAGE 1's model-sheet panels. Do NOT draw "
    "crying, tears, wailing, screaming, sweat drops, or the character's default comic "
    "distress face unless IMAGE 2 shows them.\n"
    "HANDS — count and match IMAGE 2: exactly TWO hands total. If IMAGE 2 shows open "
    "palms with spread fingers, draw open palms — not fists. Do NOT add a third hand.\n"
    "DEPTH & FORESHORTENING — CRITICAL: copy the 3D depth from IMAGE 2 exactly. The foot "
    "or hand closest to the camera must be drawn LARGER than the far foot/hand by the SAME "
    "ratio IMAGE 2 shows. Do NOT flatten both feet to equal size. Do NOT over-exaggerate "
    "one foot beyond what IMAGE 2 shows. Preserve which leg is near vs far."
)

# Anchor when rough+canny mode: images are target(1), rough(2), canny(3), anchor(4).
CONSISTENCY_REF_ROUGH_CANNY = (
    "\nIMAGE 4 is the ANCHOR: an approved frame from THIS SAME sequence. Use IMAGE 4 ONLY "
    "for DESIGN consistency — never for pose or camera framing:\n"
    "- DESIGN LOCK: same hairstyle, outfit, line weight, and accessory detail sizes as in "
    "IMAGE 4.\n"
    "- ACCESSORY PLACEMENT: every accessory must appear in the SAME place and worn the "
    "SAME way as in IMAGE 4 and IMAGE 1.\n"
    "- DO NOT use IMAGE 4 for framing, camera scale, or vertical position — those come "
    "entirely from IMAGE 2 and IMAGE 3 for THIS frame.\n"
    "POSE comes from IMAGE 2 (structure/framing from IMAGE 3). DO NOT copy IMAGE 4's pose. "
    "These are consecutive animation frames — reproduce the small pose differences IMAGE 2 "
    "shows versus the anchor."
)

# Option 2 — rolling previous frame (frame 2+): target(1), rough(2), canny(3), previous(4).
CONSISTENCY_REF_PREVIOUS_ROUGH_CANNY = (
    "\nIMAGE 4 is the PREVIOUS FRAME: the immediately prior approved output from THIS SAME "
    "sequence. Use IMAGE 4 ONLY for style and design continuity — NEVER for pose:\n"
    "- STYLE LOCK: match IMAGE 4's THIN line weight, level of detail, and how clothing/accessories "
    "are drawn. Lines must stay thin and delicate — never bolder than IMAGE 4.\n"
    "- DESIGN LOCK: keep the same outfit, hair, and accessory rendering as IMAGE 4 and IMAGE 1.\n"
    "- MOTION CONTEXT: IMAGE 4 shows where the character WAS one frame ago; IMAGE 2 shows "
    "where they are NOW. Reproduce the small pose change between them.\n"
    "- DO NOT copy IMAGE 4's pose, limb angles, head tilt, or body lean — pose comes "
    "ENTIRELY from IMAGE 2 (framing from IMAGE 3).\n"
    "Character identity from IMAGE 1. Pose from IMAGE 2. Framing from IMAGE 3."
)

# --- how the output is drawn. The client gave BOTH kinds of example, so it is a knob.
#  rough : match the loose blue rough-animation sketch (the Luffy example)
#  clean : fully rendered flat-color anime cel (the Rias example)
_COMMON = (
    "You are a professional 2D anime animation assistant.\n"
    "IMAGE 1 is a CHARACTER MODEL SHEET. It defines WHO the character is and nothing "
    "else: their face, hairstyle, hair colour, outfit/clothing, and signature "
    "accessories (e.g. a hat). Study every view so the character stays on-model.\n"
    "IMAGE 2 is a ROUGH GESTURE SKETCH. It defines ONLY the pose: body position, the "
    "action, limb placement, body orientation and camera angle. IGNORE image 2's body "
    "type, gender, proportions and identity -- it is a pose reference, not a character.\n"
    "TASK: Draw the IMAGE 1 character performing the EXACT pose and action from IMAGE 2. "
    "It must be instantly recognisable as the IMAGE 1 character -- correct face, hair, "
    "outfit and accessories -- while precisely matching the IMAGE 2 pose.\n"
    "POSE FIDELITY IS CRITICAL -- copy the skeleton of IMAGE 2 joint-for-joint. Match the "
    "exact bend of every limb, which leg is planted and which is raised, the exact height "
    "and angle of each limb, the torso lean, the hip/shoulder line and the head direction. "
    "PRESERVE which limbs are BENT vs STRAIGHT: if a knee is raised and bent (knee up, "
    "lower leg tucked), keep it raised and bent -- do NOT straighten or extend it into a "
    "kick. Do NOT redesign, dramatise, 'improve', mirror or re-angle the pose in any way. "
    "The silhouette must overlay the IMAGE 2 gesture.\n"
    "ARMS AND HANDS -- read them carefully and copy them exactly: where each shoulder, "
    "elbow, wrist and hand sits, whether each arm is raised, lowered, extended out, bent, "
    "crossed or tucked, and which direction each hand points. Do NOT invent a different "
    "arm pose (for example, do NOT put both hands behind the head unless IMAGE 2 shows "
    "that).\n"
    "HAND SHAPE -- match each hand to the rough EXACTLY and symmetrically: if the rough "
    "shows a FIST, draw a fist; if it shows an open palm, spread fingers, a pointing "
    "finger or an OK/pinch sign, draw exactly that. Do NOT swap a fist for an open hand or "
    "an open hand for a fist, and do NOT invent a gesture the rough does not show. Do NOT "
    "default both hands to fists — read IMAGE 2 and copy each hand independently.\n"
    "LIMB COUNT — CRITICAL: the character has EXACTLY two arms and two legs in every "
    "frame. Draw ONLY the limbs IMAGE 2 shows. Overlapping rough strokes, construction "
    "circles at joints, and correction lines are NOT extra limbs — never add a third arm, "
    "phantom hand, or duplicate leg. Each arm connects shoulder → elbow → wrist → ONE hand.\n"
    "FACIAL EXPRESSION — copy IMAGE 2's face EXACTLY, NOT IMAGE 1's model-sheet faces. "
    "Match the rough's eye size/shape, eyebrow angle, and mouth shape. Use a simple "
    "surprised/alarmed/shocked reaction as the rough shows (wide eyes, small open mouth). "
    "Do NOT use the character's default comic crying, wailing, screaming or tearful face. "
    "No tears, no tear drops, no wavy crying mouth, no scrunched crying eyes unless "
    "IMAGE 2 explicitly shows them.\n"
    "DEPTH & FORESHORTENING: preserve the near/far limb size relationship from IMAGE 2. "
    "The limb closest to the camera is larger; the far limb is smaller. Never equalize "
    "both feet or both hands to the same size when IMAGE 2 shows foreshortening.\n"
    "BODY LEAN & LEGS: copy the exact torso lean (how far the upper body reclines or "
    "leans), how deeply the knees are bent and how high the legs are pulled up, and which "
    "way the body FACES (front, back or three-quarter). Do not straighten a reclined torso "
    "or lower raised knees.\n"
    "FRAMING -- CRITICAL FOR ANIMATION SEQUENCES: keep the character at the SAME "
    "position, the SAME scale and the SAME camera framing as in IMAGE 2. Do NOT re-centre "
    "the figure, do NOT zoom in or out, do NOT crop or re-compose. The character must "
    "occupy exactly the same place and the same size within the frame as it does in the "
    "rough, so that consecutive frames of a sequence line up perfectly when played back. "
    "Match IMAGE 2's empty space and margins.\n"
    "CHARACTER CONSISTENCY -- CRITICAL FOR SEQUENCES: draw the character IDENTICALLY in "
    "every frame. Take the canonical look from the model sheet's MAIN FULL-BODY FRONT "
    "view and use that same look every single time. Every accessory the character has "
    "(hat, cape, glasses, weapon, ribbon) must appear in EVERY frame, worn the SAME way in "
    "the SAME place -- never omit an accessory in one frame and add it in another, and "
    "never relocate it (e.g. if the hat sits on the head in that front view it stays on "
    "the head in every frame; if it hangs on the back it stays on the back in every "
    "frame). For Luffy action frames: the straw hat ALWAYS hangs on the BACK/NECK on a "
    "string — NEVER on the head (ignore the 'happy face' model-sheet panel for hat "
    "placement in these poses). Keep the hairstyle, outfit, accessories, body proportions "
    "and line weight exactly the same across all frames.\n"
    "Single full-body character, plain solid white background, no text, no watermark, no "
    "extra characters, no split panels.\n"
)
STYLES = {
    "rough": _COMMON + (
        "RENDER STYLE: a single loose ROUGH ANIMATION SKETCH -- clean blue pencil line "
        "art on white, in the same rough hand-drawn sketch style as IMAGE 2. Line work "
        "only, NO colour fills, NO shading. Keep it a rough/tie-down, not a finished drawing."
    ),
    "line": _COMMON + (
        "RENDER STYLE: PURE UNCOLOURED LINE ART -- the tie-down / clean-up stage of "
        "animation. Draw ONLY outlines: every contour is ONE smooth, confident, precise "
        "single-weight stroke in PURE BLACK, on a pure white background. No rough, scratchy "
        "or overlapping construction lines -- perfectly clean line work.\n"
        "LINE WEIGHT — CRITICAL: use clean, smooth, uniform animation tie-down lines. "
        "NOT rough, scratchy, dotted or broken strokes.\n"
        "LINE QUALITY — CRITICAL: every outline must be a CONTINUOUS, UNBROKEN, CLOSED "
        "stroke — like professional animation clean-up inked on cel. NO dotted, dashed, "
        "broken, gap-filled, stippled or scratchy lines. NO missing segments in contours. "
        "Hair strands, clothing edges and boot outlines must be smooth solid curves with "
        "no gaps.\n"
        "ABSOLUTELY NO COLOUR AND NO FILLS ANYWHERE. The entire image must be PURE BLACK "
        "lines on PURE WHITE only — no blue, no red, no skin tone, no hair colour, no tinted "
        "accessories, no grey fills, no gradients, no shadows. Even small gems, ribbons, "
        "capelets, skirts, boots or beads must be drawn as black OUTLINE only — never filled "
        "with colour or solid black.\n"
        "IGNORE IMAGE 1's COLOURS for rendering. The model sheet may show flat cel colours "
        "(red hair, dark skirt, coloured cape) — do NOT copy those fills. Copy ONLY the "
        "character's design shapes from IMAGE 1, then draw them as unfilled black outlines.\n"
        "THE HAIR MUST NOT BE FILLED IN. Draw the hair as OUTLINES ONLY -- its silhouette "
        "and a few strand lines -- leaving the inside of the hair PURE WHITE. Never render "
        "hair, a hat, boots, a CAPE, CAPELET, SKIRT, RIBBOW, or ANY garment as a solid black "
        "or grey shape, even if it is dark in the model sheet -- draw its OUTLINE only and "
        "leave the inside white. There are NO solid black or filled areas of any kind in "
        "this drawing.\n"
        "Every region enclosed by the lines stays PURE WHITE. The ONLY dark pixels in the "
        "entire image are the thin contour strokes themselves. This is an uncoloured, "
        "unfilled line drawing -- a clean-up/tie-down, NOT a painting and NOT an inked "
        "illustration with black masses.\n"
        "Do NOT add hat weave hatching, cross-hatching, stipple, or interior texture lines. "
        "The straw hat is a simple outline with a band line only."
    ),
    "clean": _COMMON + (
        "RENDER STYLE: a fully finished, clean anime illustration -- crisp black line art "
        "with flat cel colours taken from the IMAGE 1 colour palette, professional, "
        "on-model, high quality."
    ),
}
